"""Behavioural ownership regressions; network and writes are mocked."""
import copy
import os
import unittest
from unittest.mock import patch
os.environ.setdefault('GH_TOKEN','unit-test')
os.environ.setdefault('GITHUB_REPOSITORY','owner/repo')
import trusted_automation as admission
import branch_pr_automation as branches

class OwnershipTests(unittest.TestCase):
    def setUp(self):
        self.status = self.enterContext(patch.object(admission, 'emit_admission_status'))
        self.enterContext(patch.object(admission, 'revoke_admission'))
        self.pr={'number':8,'state':'open','draft':False,'user':{'login':'renovate[bot]'},'head':{'ref':'renovate/example','sha':'a'*40,'repo':{'full_name':admission.REPO}},'base':{'ref':admission.DEFAULT_BRANCH},'labels':[{'name':'dependency:auto-eligible'}],'body':'This PR was generated by [Mend Renovate]\n<!--renovate-debug: data -->'}
    def test_explicit_eligibility_does_not_need_automerge_body(self):
        self.assertTrue(admission.renovate_auto_eligible(self.pr))
    def test_obsolete_automerge_body_does_not_admit(self):
        self.pr['labels']=[];self.pr['body']+='\n**Automerge**: Enabled.'
        self.assertFalse(admission.renovate_auto_eligible(self.pr))
    def test_manual_wins_over_safe_label(self):
        self.pr['labels'].append({'name':'dependency:manual'})
        self.assertFalse(admission.renovate_auto_eligible(self.pr))
    def test_fork_or_impostor_is_not_eligible(self):
        self.pr['head']['repo']['full_name']='fork/repo'
        self.assertFalse(admission.renovate_auto_eligible(self.pr))
        self.pr['head']['repo']['full_name']=admission.REPO
        self.pr['user']['login']='impostor'
        self.assertFalse(admission.renovate_auto_eligible(self.pr))
    def test_wrong_namespace_is_not_eligible(self):
        self.pr['head']['ref']='fix/update'
        self.assertFalse(admission.renovate_auto_eligible(self.pr))
    def test_native_merge_and_mergify_cannot_be_armed_together(self):
        self.pr['auto_merge']={'enabled':True}
        with patch.object(admission,'admit_to_mergify') as admit:
            admission.reconcile_pr(self.pr)
        admit.assert_not_called()
    def test_required_checks_gate_admission(self):
        with patch.object(admission,'all_required_checks_green',return_value=(False,'pending')),patch.object(admission,'admit_to_mergify') as admit:
            admission.reconcile_pr(self.pr)
        admit.assert_not_called()
    def test_head_change_revokes_candidate(self):
        with patch.object(admission,'all_required_checks_green',return_value=(True,'green')),patch.object(admission,'current_head_unchanged',return_value=None),patch.object(admission,'admit_to_mergify') as admit:
            admission.reconcile_pr(self.pr)
        admit.assert_not_called()
    def test_ordinary_lane_excludes_all_automation(self):
        for name in ['renovate/a','dependabot/a','autonomy/a','mergify/a','codex/task','automation/revert','tmp/a','internal/a']:
            with self.subTest(name=name):self.assertFalse(branches.allowed_branch(name))
        self.assertTrue(branches.allowed_branch('fix/application'))
    def test_kilo_cannot_write_dependency_manifests(self):
        self.pr['user']['login']=admission.KILO_LOGIN
        self.pr['labels']=[{'name':'autonomy:repair'},{'name':'autonomy:kilo-implementation'}]
        with patch.object(admission,'pr_files',return_value=['package.json']),patch.object(admission,'place_human_hold') as hold,patch.object(admission,'admit_to_mergify') as admit:
            admission.reconcile_pr(self.pr)
        hold.assert_called_once();admit.assert_not_called()
    def test_protected_baselines_and_admission_code_are_protected(self):
        for name in ['.gitleaksignore','.github/scripts/trusted_automation.py','renovate.json','socket.yml','codecov.yml']:
            self.assertTrue(admission.sensitive_file(name))


    def test_admission_binds_proof_to_expected_sha(self):
        with patch.object(admission, 'current_head_unchanged', return_value=self.pr), patch.object(admission, 'add_labels') as labels:
            admission.admit_to_mergify(8, 'a'*40)
        self.status.assert_called_once_with(8, 'a'*40, 'success', 'Exact-head identity, policy and required CI/security verified')
        labels.assert_called_once_with(8, ['autonomy:admitted'])
    def test_manual_label_prevents_proof_even_after_checks(self):
        self.pr['labels'].append({'name':'dependency:manual'})
        with patch.object(admission, 'current_head_unchanged', return_value=self.pr), patch.object(admission, 'add_labels') as labels:
            admission.admit_to_mergify(8, 'a'*40)
        self.status.assert_not_called();labels.assert_not_called()
    def test_changed_head_cannot_get_proof_or_admission(self):
        with patch.object(admission, 'current_head_unchanged', return_value=None), patch.object(admission, 'add_labels') as labels:
            admission.admit_to_mergify(8, 'a'*40)
        self.status.assert_not_called();labels.assert_not_called()

if __name__=='__main__':unittest.main()
