#!/usr/bin/env python3
"""Admit only verified automation pull requests.

Runs from the trusted default-branch workflow. It never checks out or executes PR code.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any

API = "https://api.github.com"
TOKEN = os.environ["GH_TOKEN"]
REPO = os.environ.get("REPO") or os.environ["GITHUB_REPOSITORY"]
REQUIRED_WORKFLOWS = [x.strip() for x in os.environ.get("REQUIRED_WORKFLOWS", "").split("|") if x.strip()]
DEFAULT_BRANCH = os.environ.get("DEFAULT_BRANCH", "main")
REPAIR_APP_LOGIN = os.environ.get("REPAIR_APP_LOGIN", "")

RENOVATE_LOGIN = "renovate[bot]"
KILO_LOGIN = os.environ.get("KILO_REPAIR_PR_LOGIN") or "kilo-code-bot[bot]"
CARRIER_PREFIX = "[autonomy] Repair "
URL_END = r"(?![A-Za-z0-9/_-])"

KILO_SENSITIVE_PREFIXES = (
    ".github/workflows/",
    ".github/actions/",
    ".github/scripts/",
    "codecov.yml",
    "socket.yml",
    ".council/",
    ".lychee",
    "zizmor",
    ".github/CODEOWNERS",
    ".github/dependabot.yml",
    ".mergify.yml",
    "renovate.json",
    ".gitleaks",
    "SECURITY.md",
    "AUTONOMY.md",
    "CI_SETUP.txt",
)
KILO_SENSITIVE_EXACT = {
    "scripts/secret_scan.py",
    "scripts/install_ci_tools.py",
    "scripts/verify_ci_tool_checksums.py",
}


def log(message: str) -> None:
    print(message, flush=True)


@dataclass
class ApiError(RuntimeError):
    status: int
    body: str

    def __str__(self) -> str:
        return f"GitHub API HTTP {self.status}: {self.body[:500]}"


def request(method: str, path: str, data: Any | None = None, expected: tuple[int, ...] = (200,)) -> Any:
    url = path if path.startswith("http") else API + path
    payload = None if data is None else json.dumps(data).encode("utf-8")
    req = urllib.request.Request(url, data=payload, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Authorization", f"Bearer {TOKEN}")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    if payload is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read()
            if resp.status not in expected:
                raise ApiError(resp.status, raw.decode("utf-8", "replace"))
            if not raw:
                return None
            return json.loads(raw.decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", "replace")
        raise ApiError(exc.code, body) from exc


def get(path: str) -> Any:
    return request("GET", path, expected=(200,))


def post(path: str, data: Any | None = None, expected: tuple[int, ...] = (200, 201, 202, 204)) -> Any:
    return request("POST", path, data=data, expected=expected)


def delete(path: str, expected: tuple[int, ...] = (200, 204)) -> Any:
    return request("DELETE", path, expected=expected)


def issue_labels(pr: dict[str, Any]) -> set[str]:
    return {str(x.get("name", "")) for x in pr.get("labels", [])}


def ensure_label(name: str, color: str, description: str) -> None:
    try:
        post(f"/repos/{REPO}/labels", {"name": name, "color": color, "description": description}, expected=(201,))
    except ApiError as exc:
        if exc.status != 422:  # already exists is returned as validation failure
            raise


def add_labels(number: int, labels: list[str]) -> None:
    post(f"/repos/{REPO}/issues/{number}/labels", {"labels": labels}, expected=(200,))


def comment(number: int, body: str) -> None:
    post(f"/repos/{REPO}/issues/{number}/comments", {"body": body}, expected=(201,))


def list_open_prs() -> list[dict[str, Any]]:
    prs: list[dict[str, Any]] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/pulls?state=open&per_page=100&page={page}")
        prs.extend(chunk)
        if len(chunk) < 100:
            return prs
    raise RuntimeError("More than 1,000 open PRs; refusing incomplete trust reconciliation")


def is_same_repo(pr: dict[str, Any]) -> bool:
    return str(pr.get("head", {}).get("repo", {}).get("full_name", "")) == REPO


def is_renovate(pr: dict[str, Any]) -> bool:
    body = pr.get("body") or ""
    return (
        pr.get("user", {}).get("login") == RENOVATE_LOGIN
        and is_same_repo(pr)
        and "This PR was generated by [Mend Renovate]" in body
        and "<!--renovate-debug:" in body
    )


def renovate_auto_eligible(pr: dict[str, Any]) -> bool:
    return (is_renovate(pr) and str(pr.get("head", {}).get("ref", "")).startswith("renovate/")
            and "dependency:auto-eligible" in issue_labels(pr)
            and not issue_labels(pr).intersection({"dependency:manual", "needs-manual-review", "do-not-merge"}))


renovate_automerge_enabled = renovate_auto_eligible

def is_repair_carrier_identity(pr: dict[str, Any]) -> bool:
    """Identify a repair carrier regardless of lifecycle labels."""
    return (
        pr.get("user", {}).get("login") == REPAIR_APP_LOGIN
        and pr.get("state") == "open"
        and is_same_repo(pr)
        and pr.get("base", {}).get("ref") == DEFAULT_BRANCH
        and str(pr.get("title", "")).startswith(CARRIER_PREFIX)
        and re.fullmatch(r"autonomy/repair-\d+", str(pr.get("head", {}).get("ref", ""))) is not None
        and bool(issue_labels(pr).intersection({"autonomy:repair", "autonomy:obsolete", "autonomy:superseded"}))
    )


def is_carrier(pr: dict[str, Any]) -> bool:
    labels = issue_labels(pr)
    return (
        is_repair_carrier_identity(pr)
        and not labels.intersection({"autonomy:human-hold", "autonomy:superseded", "autonomy:obsolete"})
    )


def carrier_comments(number: int) -> list[dict[str, Any]]:
    comments: list[dict[str, Any]] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/issues/{number}/comments?per_page=100&page={page}")
        comments.extend(chunk)
        if len(chunk) < 100:
            return comments
    raise RuntimeError(f"PR #{number} has too many comments to verify safely")


def linked_kilo_carrier(pr: dict[str, Any], carriers: list[dict[str, Any]]) -> int | None:
    if pr.get("user", {}).get("login") != KILO_LOGIN or not is_same_repo(pr):
        return None
    pr_url = str(pr.get("html_url", ""))
    body = pr.get("body") or ""
    for carrier in carriers:
        carrier_url = str(carrier.get("html_url", ""))
        if carrier_url and re.search(re.escape(carrier_url) + URL_END, body):
            return int(carrier["number"])
        try:
            comments = carrier_comments(int(carrier["number"]))
        except ApiError as exc:
            log(f"Carrier #{carrier['number']} comments unavailable: {exc}")
            continue
        for item in comments:
            text = item.get("body") or ""
            if item.get("user", {}).get("login") == KILO_LOGIN and pr_url and re.search(re.escape(pr_url) + URL_END, text):
                return int(carrier["number"])
    return None


def linked_kilo_review_source(pr: dict[str, Any], sources: list[dict[str, Any]]) -> int | None:
    """Require the exact-head receipt and preserve the complete source PR history."""
    if pr.get("user", {}).get("login") != KILO_LOGIN or not is_same_repo(pr):
        return None
    body = pr.get("body") or ""
    for source in sources:
        if source.get("user", {}).get("login") == KILO_LOGIN or not is_same_repo(source):
            continue
        source_url = str(source.get("html_url", ""))
        sha = str(source.get("head", {}).get("sha", ""))
        if not source_url or not re.search(re.escape(source_url) + URL_END, body) or not sha:
            continue
        try:
            comments = carrier_comments(int(source["number"]))
        except ApiError as exc:
            log(f"Source PR #{source['number']} comments unavailable: {exc}")
            continue
        if not any(item.get("user", {}).get("login") == "github-actions[bot]" and
                   f"<!-- kilo-auto-repair:{sha}:" in (item.get("body") or "")
                   for item in comments):
            continue
        implementation_sha = str(pr.get("head", {}).get("sha", ""))
        if not re.fullmatch(r"[0-9a-f]{40}", sha) or not re.fullmatch(r"[0-9a-f]{40}", implementation_sha):
            continue
        comparison = get(f"/repos/{REPO}/compare/{sha}...{implementation_sha}")
        if comparison.get("behind_by") == 0 and comparison.get("status") in {"ahead", "identical"}:
            return int(source["number"])
        log(f"Kilo PR #{pr['number']} does not contain current source PR #{source['number']} head {sha[:12]}.")
    return None


def adopt_linked_kilo_prs(open_prs: list[dict[str, Any]]) -> None:
    carriers = [pr for pr in open_prs if is_carrier(pr)]
    for pr in open_prs:
        if pr.get("user", {}).get("login") != KILO_LOGIN:
            continue
        labels = issue_labels(pr)
        if "autonomy:kilo-implementation" in labels:
            continue
        source = linked_kilo_carrier(pr, carriers)
        if source is None:
            source = linked_kilo_review_source(pr, open_prs)
        if source is None:
            log(f"Kilo PR #{pr['number']} has no verified repair source; leaving it untrusted.")
            continue
        add_labels(int(pr["number"]), ["autonomy:repair", "autonomy:kilo-implementation"])
        log(f"Trusted Kilo implementation PR #{pr['number']} linked to source PR #{source}.")


def automation_kind(pr: dict[str, Any]) -> str | None:
    labels = issue_labels(pr)
    if is_renovate(pr):
        return "renovate"
    if is_carrier(pr):
        return "carrier"
    if (pr.get("user", {}).get("login") == KILO_LOGIN and is_same_repo(pr) and
            "autonomy:kilo-implementation" in labels and "autonomy:repair" in labels):
        return "kilo"
    return None


def current_pr_for_sha(open_prs: list[dict[str, Any]], sha: str) -> dict[str, Any] | None:
    matches = [pr for pr in open_prs if pr.get("head", {}).get("sha") == sha]
    eligible = [pr for pr in matches if automation_kind(pr)]
    return eligible[0] if len(eligible) == 1 else None


def admit_waiting_runs(open_prs: list[dict[str, Any]]) -> None:
    payload = get(f"/repos/{REPO}/actions/runs?status=action_required&per_page=100")
    runs = payload.get("workflow_runs", []) if isinstance(payload, dict) else []
    carriers = [source for source in open_prs if is_carrier(source)]
    for run in runs:
        sha = str(run.get("head_sha", ""))
        pr = current_pr_for_sha(open_prs, sha)
        if pr is None:
            continue
        kind = automation_kind(pr)
        if kind == "kilo" and (linked_kilo_carrier(pr, carriers) is None and
                                linked_kilo_review_source(pr, open_prs) is None):
            continue
        run_id = int(run["id"])
        name = str(run.get("name", "workflow"))
        try:
            post(f"/repos/{REPO}/actions/runs/{run_id}/approve", expected=(201,))
            log(f"Approved waiting {name} run {run_id} for trusted {kind} PR #{pr['number']}.")
            continue
        except ApiError as exc:
            if exc.status not in (403, 404, 409, 422):
                raise
            log(f"Approval endpoint did not accept run {run_id} ({exc.status}); trying safe rerun for the same trusted PR.")
        try:
            post(f"/repos/{REPO}/actions/runs/{run_id}/rerun", expected=(201,))
            log(f"Re-requested {name} run {run_id} for trusted {kind} PR #{pr['number']}.")
        except ApiError as exc:
            log(f"Could not automatically admit run {run_id}: {exc}")


def latest_runs_for_sha(sha: str) -> dict[str, dict[str, Any]]:
    query = urllib.parse.urlencode({"head_sha": sha, "event": "pull_request", "per_page": 100})
    payload = get(f"/repos/{REPO}/actions/runs?{query}")
    latest: dict[str, dict[str, Any]] = {}
    for run in payload.get("workflow_runs", []):
        name = str(run.get("name", ""))
        current = latest.get(name)
        if current is None or int(run.get("id", 0)) > int(current.get("id", 0)):
            latest[name] = run
    return latest


def all_required_checks_green(pr: dict[str, Any]) -> tuple[bool, str]:
    sha = str(pr.get("head", {}).get("sha", ""))
    runs = latest_runs_for_sha(sha)
    for name in REQUIRED_WORKFLOWS:
        run = runs.get(name)
        if run is None:
            return False, f"required workflow {name!r} has not run on {sha[:12]}"
        if run.get("status") != "completed" or run.get("conclusion") != "success":
            return False, f"required workflow {name!r} is {run.get('status')}/{run.get('conclusion')}"

    # GitHub's native ruleset/auto-merge checks any additional required contexts.
    # Optional review, link and external-service checks cannot become an extra gate here.
    return True, "required CI and security workflows succeeded"


def pr_files(number: int) -> list[str]:
    names: list[str] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/pulls/{number}/files?per_page=100&page={page}")
        names.extend(str(item.get("filename", "")) for item in chunk)
        if len(chunk) < 100:
            return names
    raise RuntimeError(f"PR #{number} has too many changed files to verify safely")


def dependency_manifest(path: str) -> bool:
    name = path.rsplit("/", 1)[-1]
    return (name in {"package.json", "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "pyproject.toml", "poetry.lock", "uv.lock", "Pipfile", "Pipfile.lock", "Dockerfile"}
            or name.startswith("requirements") and name.endswith((".txt", ".in", ".lock")))


def sensitive_file(path: str) -> bool:
    if path in KILO_SENSITIVE_EXACT:
        return True
    return any(path == prefix or path.startswith(prefix) for prefix in KILO_SENSITIVE_PREFIXES)


def place_human_hold(pr: dict[str, Any], reason: str) -> None:
    labels = issue_labels(pr)
    if "autonomy:human-hold" not in labels:
        add_labels(int(pr["number"]), ["autonomy:human-hold"])
        comment(int(pr["number"]), f"Trusted automation stopped here and applied `autonomy:human-hold`: {reason}")
    log(f"PR #{pr['number']} requires human review: {reason}")


def current_head_unchanged(number: int, expected_sha: str) -> dict[str, Any] | None:
    current = get(f"/repos/{REPO}/pulls/{number}")
    if current.get("state") != "open" or current.get("head", {}).get("sha") != expected_sha:
        return None
    return current


def has_current_approval(number: int, sha: str) -> bool:
    reviews = get(f"/repos/{REPO}/pulls/{number}/reviews?per_page=100")
    return any(r.get("state") == "APPROVED" and r.get("commit_id") == sha for r in reviews)


def approve_pr(number: int, sha: str) -> None:
    if has_current_approval(number, sha):
        return
    post(
        f"/repos/{REPO}/pulls/{number}/reviews",
        {
            "event": "APPROVE",
            "body": "Trusted automation approval: exact-head CI, CodeQL and repository security checks passed.",
            "commit_id": sha,
        },
        expected=(200, 201),
    )
    log(f"Approved PR #{number} at {sha[:12]} after trusted checks passed.")


def emit_admission_status(number: int, sha: str, state: str, reason: str) -> None:
    """Publish an exact-head proof from the trusted default-branch controller only."""
    token = os.environ.get("ADMISSION_STATUS_TOKEN", "")
    if not token or not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise RuntimeError("A scoped admission status token and exact head SHA are required")
    payload = {"state": state, "context": "Trusted automation admission",
               "description": reason[:140],
               "target_url": f"https://github.com/{REPO}/pull/{number}"}
    req = urllib.request.Request(f"{API}/repos/{REPO}/statuses/{sha}",
                                 data=json.dumps(payload).encode(), method="POST")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=30) as response:
        if response.status != 201:
            raise RuntimeError("Could not publish exact-head admission proof")


def revoke_admission(pr: dict[str, Any]) -> None:
    if "autonomy:admitted" in issue_labels(pr):
        delete(f"/repos/{REPO}/issues/{pr['number']}/labels/autonomy%3Aadmitted", expected=(200, 204))


def admit_to_mergify(number: int, expected_sha: str) -> None:
    pr = current_head_unchanged(number, expected_sha)
    if pr is None or pr.get("draft") or pr.get("auto_merge"):
        return
    labels = issue_labels(pr)
    if labels.intersection({"dependency:manual", "needs-manual-review", "do-not-merge", "autonomy:human-hold", "autonomy:superseded", "autonomy:obsolete"}):
        revoke_admission(pr)
        return
    if automation_kind(pr) == "renovate" and not renovate_auto_eligible(pr):
        revoke_admission(pr)
        return
    emit_admission_status(number, expected_sha, "success", "Exact-head identity, policy and required CI/security verified")
    if current_head_unchanged(number, expected_sha) is None:
        return
    if "autonomy:admitted" not in labels:
        add_labels(number, ["autonomy:admitted"])
    log(f"Admitted PR #{number} at {expected_sha[:12]}; Mergify requires the same-head proof.")


def reconcile_stale_carriers(open_prs: list[dict[str, Any]]) -> None:
    """Close verified retired carriers directly, without waiting for Mergify.

    Retired carrier branches are retained as failure evidence. Implementations
    and arbitrary PRs are never closed by this lifecycle reconciler.
    """
    branch = get(f"/repos/{REPO}/branches/{DEFAULT_BRANCH}")
    current_main_sha = str(branch.get("commit", {}).get("sha", ""))
    if not re.fullmatch(r"[0-9a-f]{40}", current_main_sha):
        raise RuntimeError("Could not resolve the current default-branch SHA")

    for pr in open_prs:
        if not is_repair_carrier_identity(pr):
            continue
        labels = issue_labels(pr)
        retired = bool(labels.intersection({"autonomy:superseded", "autonomy:obsolete"}))
        match = re.search(r"Failed commit:\s*`([0-9a-f]{40})`", str(pr.get("body") or ""))
        if not retired and (match is None or match.group(1) == current_main_sha):
            continue
        number = int(pr["number"])
        if not retired:
            add_labels(number, ["autonomy:obsolete"])
        request("PATCH", f"/repos/{REPO}/pulls/{number}", {"state": "closed"})
        # Close before removing active labels so a failed close remains retryable.
        for label in ("autonomy:human-hold", "autonomy:repair", "autonomy:admitted"):
            if label in labels:
                encoded = urllib.parse.quote(label, safe="")
                delete(f"/repos/{REPO}/issues/{number}/labels/{encoded}", expected=(200, 204))
        log(f"Closed retired repair carrier PR #{number}.")


def reconcile_pr(pr: dict[str, Any]) -> None:
    kind = automation_kind(pr)
    if is_same_repo(pr) and (kind is not None or "autonomy:admitted" in issue_labels(pr)):
        emit_admission_status(int(pr["number"]), str(pr.get("head", {}).get("sha", "")), "pending", "Revalidating exact-head automation admission")
        revoke_admission(pr)
    if kind is None or pr.get("draft"):
        return
    labels = issue_labels(pr)
    if labels.intersection({"autonomy:human-hold", "autonomy:superseded", "autonomy:obsolete"}):
        return
    if kind == "carrier":
        # Carriers record the failed run and remain blocked until the linked
        # implementation succeeds. Never merge one just because its marker was removed.
        log(f"Carrier PR #{pr['number']} is lifecycle evidence; withholding auto-merge.")
        return

    if pr.get("auto_merge"):
        log(f"PR #{pr['number']} is armed for native auto-merge; withholding Mergify admission.")
        return

    if kind == "renovate" and not renovate_auto_eligible(pr):
        # Major/manual Renovate PRs may run CI automatically, but remain human merge decisions.
        return

    if kind == "kilo":
        changed = pr_files(int(pr["number"]))
        dependency_files = [path for path in changed if dependency_manifest(path)]
        if dependency_files:
            place_human_hold(pr, "Renovate owns dependency manifests and locks: " + ", ".join(dependency_files[:8]))
            return
        sensitive = [path for path in changed if sensitive_file(path)]
        if sensitive:
            place_human_hold(pr, "the repair changes governance/security automation files: " + ", ".join(sensitive[:8]))
            return

    if kind == "kilo":
        carriers = [source for source in list_open_prs() if is_carrier(source)]
        if (linked_kilo_carrier(pr, carriers) is None and
                linked_kilo_review_source(pr, list_open_prs()) is None):
            log(f"Kilo PR #{pr['number']} no longer has a current verified source; withholding merge.")
            return

    green, reason = all_required_checks_green(pr)
    if not green:
        log(f"PR #{pr['number']} ({kind}) not ready: {reason}.")
        return

    number = int(pr["number"])
    sha = str(pr.get("head", {}).get("sha", ""))
    current = current_head_unchanged(number, sha)
    if current is None:
        log(f"PR #{number} changed while being evaluated; waiting for the next reconciliation.")
        return

    # Renovate and Kilo are distinct identities, so the repair App can provide the trusted review.
    # Carrier PRs are authored by the same repair App and GitHub correctly forbids self-approval.
    if kind in {"renovate", "kilo"}:
        approve_pr(number, sha)
        if current_head_unchanged(number, sha) is None:
            return

    admit_to_mergify(number, sha)


def main() -> int:
    if not REQUIRED_WORKFLOWS:
        raise RuntimeError("REQUIRED_WORKFLOWS must list the repository's CI/security workflow names")
    if not re.fullmatch(r"[A-Za-z0-9-]+\[bot\]", REPAIR_APP_LOGIN):
        raise RuntimeError("REPAIR_APP_LOGIN must be the installed repair GitHub App bot login")
    if (not re.fullmatch(r"[A-Za-z0-9-]+(?:\[bot\])?", KILO_LOGIN) or
            KILO_LOGIN in {REPAIR_APP_LOGIN, RENOVATE_LOGIN, "github-actions[bot]"}):
        raise RuntimeError("KILO_REPAIR_PR_LOGIN must name the distinct, verified Kilo PR creator")
    ensure_label("autonomy:kilo-implementation", "5319E7", "Kilo implementation PR linked to an autonomous repair carrier")
    ensure_label("autonomy:human-hold", "FBCA04", "Automation must stop for human action")
    ensure_label("autonomy:obsolete", "D4C5F9", "Repair carrier is no longer current")
    ensure_label("autonomy:admitted", "0E8A16", "Exact-head CI/security verification complete; Mergify may merge")

    open_prs = list_open_prs()
    reconcile_stale_carriers(open_prs)
    open_prs = list_open_prs()  # refresh after stale-carrier lifecycle changes
    adopt_linked_kilo_prs(open_prs)
    open_prs = list_open_prs()  # refresh labels after Kilo correlation
    admit_waiting_runs(open_prs)

    # Reconcile current trusted PRs. Runs admitted above will normally become ready on a later
    # workflow_run completion or scheduled reconciliation.
    for pr in open_prs:
        reconcile_pr(pr)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"::error::{exc}", file=sys.stderr)
        raise
