#!/usr/bin/env python3
"""Admit only verified automation pull requests to Mergify.

Runs from the trusted default-branch workflow. It never checks out or executes PR code.
"""
from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any

from repair_lease import (
    active_for_fingerprint,
    all_lease_comments,
    bind as bind_lease,
    claim as claim_lease,
    fingerprint as lease_fingerprint,
    marker_payload,
    release as release_lease,
    transfer as transfer_lease,
)

API = "https://api.github.com"
TOKEN = os.environ["GH_TOKEN"]
REPO = os.environ.get("REPO") or os.environ["GITHUB_REPOSITORY"]
REQUIRED_WORKFLOWS = [x.strip() for x in os.environ.get("REQUIRED_WORKFLOWS", "").split("|") if x.strip()]
DEFAULT_BRANCH = os.environ.get("DEFAULT_BRANCH", "main")
REPAIR_APP_LOGIN = os.environ.get("REPAIR_APP_LOGIN", "")

RENOVATE_LOGIN = "renovate[bot]"
KILO_LOGIN = os.environ.get("KILO_REPAIR_PR_LOGIN") or "kilo-code-bot[bot]"
CTO_LOGIN = "cto-new[bot]"
CARRIER_PREFIX = "[autonomy] Repair "
BRANCH_PR_LABEL = "automation:branch-pr"
BRANCH_PR_RE = re.compile(r"^(fix|feat|chore|ci|work|codex)/[A-Za-z0-9._/-]+$")
URL_END = r"(?![A-Za-z0-9/_-])"
BLOCKING_LABELS = {
    "autonomy:human-hold",
    "autonomy:superseded",
    "autonomy:obsolete",
    "do-not-merge",
    "do not merge",
    "hold",
    "needs-manual-review",
}

KILO_SENSITIVE_PREFIXES = (
    ".github/workflows/",
    ".github/actions/",
    ".github/scripts/",
    ".github/CODEOWNERS",
    ".github/dependabot.yml",
    ".mergify.yml",
    "renovate.json",
    ".gitleaks",
    "SECURITY.md",
    "AUTONOMY.md",
    "CI_SETUP.txt",
)
KILO_SENSITIVE_EXACT = {
    ".github/production-governance.json",
    "scripts/secret_scan.py",
    "scripts/install_ci_tools.py",
    "scripts/verify_ci_tool_checksums.py",
}


def log(message: str) -> None:
    print(message, flush=True)


@dataclass
class ApiError(RuntimeError):
    status: int
    body: str

    def __str__(self) -> str:
        return f"GitHub API HTTP {self.status}: {self.body[:500]}"


def request(method: str, path: str, data: Any | None = None, expected: tuple[int, ...] = (200,)) -> Any:
    url = path if path.startswith("http") else API + path
    payload = None if data is None else json.dumps(data).encode("utf-8")
    req = urllib.request.Request(url, data=payload, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Authorization", f"Bearer {TOKEN}")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    if payload is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read()
            if resp.status not in expected:
                raise ApiError(resp.status, raw.decode("utf-8", "replace"))
            if not raw:
                return None
            return json.loads(raw.decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", "replace")
        raise ApiError(exc.code, body) from exc


def get(path: str) -> Any:
    return request("GET", path, expected=(200,))


def post(path: str, data: Any | None = None, expected: tuple[int, ...] = (200, 201, 202, 204)) -> Any:
    return request("POST", path, data=data, expected=expected)


def delete(path: str, expected: tuple[int, ...] = (200, 204)) -> Any:
    return request("DELETE", path, expected=expected)


def issue_labels(pr: dict[str, Any]) -> set[str]:
    return {str(x.get("name", "")) for x in pr.get("labels", [])}


def ensure_label(name: str, color: str, description: str) -> None:
    try:
        post(f"/repos/{REPO}/labels", {"name": name, "color": color, "description": description}, expected=(201,))
    except ApiError as exc:
        if exc.status != 422:  # already exists is returned as validation failure
            raise


def add_labels(number: int, labels: list[str]) -> None:
    post(f"/repos/{REPO}/issues/{number}/labels", {"labels": labels}, expected=(200,))


def comment(number: int, body: str) -> None:
    post(f"/repos/{REPO}/issues/{number}/comments", {"body": body}, expected=(201,))


def list_open_prs() -> list[dict[str, Any]]:
    prs: list[dict[str, Any]] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/pulls?state=open&per_page=100&page={page}")
        prs.extend(chunk)
        if len(chunk) < 100:
            return prs
    raise RuntimeError("More than 1,000 open PRs; refusing incomplete trust reconciliation")


def is_same_repo(pr: dict[str, Any]) -> bool:
    return str(pr.get("head", {}).get("repo", {}).get("full_name", "")) == REPO


def is_renovate(pr: dict[str, Any]) -> bool:
    body = pr.get("body") or ""
    return (
        pr.get("user", {}).get("login") == RENOVATE_LOGIN
        and is_same_repo(pr)
        and "This PR was generated by [Mend Renovate]" in body
        and "<!--renovate-debug:" in body
    )


def renovate_auto_eligible(pr: dict[str, Any]) -> bool:
    return is_renovate(pr) and "dependency:auto-eligible" in issue_labels(pr)


def is_managed_branch_pr(pr: dict[str, Any]) -> bool:
    """Recognise trusted implementation PRs without giving them merge authority."""
    labels = issue_labels(pr)
    branch = str(pr.get("head", {}).get("ref", ""))
    return (
        pr.get("user", {}).get("login") == REPAIR_APP_LOGIN
        and pr.get("state") == "open"
        and not pr.get("draft")
        and is_same_repo(pr)
        and pr.get("base", {}).get("ref") == DEFAULT_BRANCH
        and BRANCH_PR_LABEL in labels
        and BRANCH_PR_RE.fullmatch(branch) is not None
    )


def is_repair_carrier_identity(pr: dict[str, Any]) -> bool:
    """Identify a repair carrier regardless of lifecycle labels."""
    return (
        pr.get("user", {}).get("login") == REPAIR_APP_LOGIN
        and pr.get("state") == "open"
        and is_same_repo(pr)
        and pr.get("base", {}).get("ref") == DEFAULT_BRANCH
        and str(pr.get("title", "")).startswith(CARRIER_PREFIX)
        and re.fullmatch(r"autonomy/repair-\d+", str(pr.get("head", {}).get("ref", ""))) is not None
        and bool(issue_labels(pr).intersection({"autonomy:repair", "autonomy:obsolete", "autonomy:superseded"}))
    )


def is_carrier(pr: dict[str, Any]) -> bool:
    labels = issue_labels(pr)
    return (
        is_repair_carrier_identity(pr)
        and not labels.intersection({"autonomy:human-hold", "autonomy:superseded", "autonomy:obsolete"})
    )


def carrier_comments(number: int) -> list[dict[str, Any]]:
    comments: list[dict[str, Any]] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/issues/{number}/comments?per_page=100&page={page}")
        comments.extend(chunk)
        if len(chunk) < 100:
            return comments
    raise RuntimeError(f"PR #{number} has too many comments to verify safely")


def linked_kilo_carrier(pr: dict[str, Any], carriers: list[dict[str, Any]]) -> int | None:
    if pr.get("user", {}).get("login") != KILO_LOGIN or not is_same_repo(pr):
        return None
    pr_url = str(pr.get("html_url", ""))
    body = pr.get("body") or ""
    for carrier in carriers:
        carrier_url = str(carrier.get("html_url", ""))
        if carrier_url and re.search(re.escape(carrier_url) + URL_END, body):
            return int(carrier["number"])
        try:
            comments = carrier_comments(int(carrier["number"]))
        except ApiError as exc:
            log(f"Carrier #{carrier['number']} comments unavailable: {exc}")
            continue
        for item in comments:
            text = item.get("body") or ""
            if item.get("user", {}).get("login") == KILO_LOGIN and pr_url and re.search(re.escape(pr_url) + URL_END, text):
                return int(carrier["number"])
    return None


def linked_kilo_review_source(pr: dict[str, Any], sources: list[dict[str, Any]]) -> int | None:
    """Require the exact-head receipt and preserve the complete source PR history."""
    if pr.get("user", {}).get("login") != KILO_LOGIN or not is_same_repo(pr):
        return None
    body = pr.get("body") or ""
    for source in sources:
        if source.get("user", {}).get("login") == KILO_LOGIN or not is_same_repo(source):
            continue
        source_url = str(source.get("html_url", ""))
        sha = str(source.get("head", {}).get("sha", ""))
        if not source_url or not re.search(re.escape(source_url) + URL_END, body) or not sha:
            continue
        try:
            comments = carrier_comments(int(source["number"]))
        except ApiError as exc:
            log(f"Source PR #{source['number']} comments unavailable: {exc}")
            continue
        if not any(item.get("user", {}).get("login") == "github-actions[bot]" and
                   f"<!-- kilo-auto-repair:{sha}:" in (item.get("body") or "")
                   for item in comments):
            continue
        implementation_sha = str(pr.get("head", {}).get("sha", ""))
        if not re.fullmatch(r"[0-9a-f]{40}", sha) or not re.fullmatch(r"[0-9a-f]{40}", implementation_sha):
            continue
        comparison = get(f"/repos/{REPO}/compare/{sha}...{implementation_sha}")
        if comparison.get("behind_by") == 0 and comparison.get("status") in {"ahead", "identical"}:
            return int(source["number"])
        log(f"Kilo PR #{pr['number']} does not contain current source PR #{source['number']} head {sha[:12]}.")
    return None


def adopt_linked_kilo_prs(open_prs: list[dict[str, Any]]) -> None:
    carriers = [pr for pr in open_prs if is_carrier(pr)]
    for pr in open_prs:
        if pr.get("user", {}).get("login") != KILO_LOGIN:
            continue
        labels = issue_labels(pr)
        if "autonomy:kilo-implementation" in labels:
            continue
        source = linked_kilo_carrier(pr, carriers)
        if source is None:
            source = linked_kilo_review_source(pr, open_prs)
        if source is None:
            log(f"Kilo PR #{pr['number']} has no verified repair source; leaving it untrusted.")
            continue
        add_labels(int(pr["number"]), ["autonomy:repair", "autonomy:kilo-implementation"])
        log(f"Trusted Kilo implementation PR #{pr['number']} linked to source PR #{source}.")

def active_leases_for_issue(number: int, owner: str | None = None) -> list[dict[str, Any]]:
    latest: dict[str, dict[str, Any]] = {}
    for item in sorted(all_lease_comments(), key=lambda row: int(row["id"])):
        payload = marker_payload(item.get("body", ""))
        if not payload or int(payload.get("source_issue", -1)) != number:
            continue
        latest[str(payload["fingerprint"])] = payload
    states = [x for x in latest.values() if x.get("status") == "active"]
    if owner is not None:
        states = [x for x in states if x.get("owner") == owner]
    return states


def reconcile_cto_tasks() -> None:
    current = get(f"/repos/{REPO}/commits/{DEFAULT_BRANCH}")
    current_sha = str(current.get("sha", ""))
    for page in range(1, 11):
        issues = get(f"/repos/{REPO}/issues?state=open&labels=autonomy%3Acto-task&per_page=100&page={page}")
        for issue in issues:
            if issue.get("pull_request"):
                continue
            number = int(issue["number"])
            body = str(issue.get("body") or "")
            category = re.search(r"(?im)^Work category:\s*\x60([^\x60]+)\x60\s*$", body)
            scope = re.search(r"(?im)^Affected path/control:\s*\x60([^\x60]+)\x60\s*$", body)
            source = re.search(r"(?im)^Source SHA:\s*\x60([0-9a-f]{40})\x60\s*$", body)
            if not category or not scope or not source:
                log(f"cto.new issue #{number} lacks the required machine task fields; no lease created.")
                continue
            if source.group(1) != current_sha:
                log(f"cto.new issue #{number} targets stale SHA {source.group(1)[:12]}; no lease created.")
                continue
            category_value = category.group(1).strip()
            scope_value = scope.group(1).strip()
            source_sha = source.group(1)
            fp = lease_fingerprint(REPO, category_value, scope_value, source_sha)
            current_lease = active_for_fingerprint(fp)
            if current_lease and current_lease.get("owner") == "cto":
                continue
            if current_lease and current_lease.get("owner") == "kilo":
                try:
                    transfer_lease(
                        number,
                        "kilo",
                        "cto",
                        category_value,
                        scope_value,
                        source_sha,
                    )
                    log(
                        f"Transferred durable ownership from Kilo to cto.new "
                        f"for actionable issue #{number}."
                    )
                except RuntimeError as exc:
                    log(
                        f"cto.new issue #{number} waits for Kilo to become inactive: "
                        f"{exc}."
                    )
                continue
            if current_lease:
                log(
                    f"cto.new issue #{number} conflicts with active owner "
                    f"{current_lease.get('owner')}; no lease created."
                )
                continue
            claim_lease(
                number,
                "cto",
                category_value,
                scope_value,
                source_sha,
            )
            log(f"Created durable cto.new lease for actionable issue #{number}.")
        if len(issues) < 100:
            break


def linked_cto_issue(pr: dict[str, Any]) -> tuple[int, dict[str, Any]] | None:
    if pr.get("user", {}).get("login") != CTO_LOGIN or not is_same_repo(pr):
        return None
    body = str(pr.get("body") or "")
    pattern = re.compile(r"https://github\.com/" + re.escape(REPO) + r"/issues/(\d+)" + URL_END)
    numbers = sorted({int(x) for x in pattern.findall(body)})
    matches: list[tuple[int, dict[str, Any]]] = []
    for number in numbers:
        issue = get(f"/repos/{REPO}/issues/{number}")
        labels = issue_labels(issue)
        if issue.get("state") != "open" or issue.get("pull_request") or "autonomy:cto-task" not in labels:
            continue
        leases = active_leases_for_issue(number, "cto")
        if len(leases) == 1:
            matches.append((number, leases[0]))
    return matches[0] if len(matches) == 1 else None


def adopt_linked_cto_prs(open_prs: list[dict[str, Any]]) -> None:
    for pr in open_prs:
        if pr.get("user", {}).get("login") != CTO_LOGIN:
            continue
        labels = issue_labels(pr)
        if "autonomy:cto-implementation" in labels:
            continue
        linked = linked_cto_issue(pr)
        if linked is None:
            log(f"cto.new PR #{pr['number']} has no single verified actionable issue/lease; leaving it untrusted.")
            continue
        issue_number, lease = linked
        bind_lease(issue_number, "cto", str(lease["fingerprint"]), int(pr["number"]))
        add_labels(int(pr["number"]), ["autonomy:cto-implementation"])
        log(f"Trusted cto.new PR #{pr['number']} linked to actionable issue #{issue_number}.")


def reconcile_completed_leases() -> None:
    latest: dict[str, dict[str, Any]] = {}
    for item in sorted(all_lease_comments(), key=lambda row: int(row["id"])):
        payload = marker_payload(item.get("body", ""))
        if payload:
            latest[str(payload["fingerprint"])] = payload
    for lease in latest.values():
        if lease.get("status") != "active":
            continue
        issue_number = int(lease.get("source_issue", 0))
        owner = str(lease.get("owner", ""))
        implementation = lease.get("implementation_pr")
        if implementation:
            pr = get(f"/repos/{REPO}/pulls/{int(implementation)}")
            if pr.get("state") != "open":
                release_lease(issue_number, owner, str(lease["fingerprint"]), "implementation-pr-closed")
                continue
        issue = get(f"/repos/{REPO}/issues/{issue_number}")
        if issue.get("state") != "open":
            release_lease(issue_number, owner, str(lease["fingerprint"]), "source-task-closed")


def automation_kind(pr: dict[str, Any]) -> str | None:
    labels = issue_labels(pr)
    if is_renovate(pr):
        return "renovate"
    if is_managed_branch_pr(pr):
        return "branch-pr"
    if is_carrier(pr):
        return "carrier"
    if (pr.get("user", {}).get("login") == KILO_LOGIN and is_same_repo(pr) and
            "autonomy:kilo-implementation" in labels and "autonomy:repair" in labels):
        return "kilo"
    if (pr.get("user", {}).get("login") == CTO_LOGIN and is_same_repo(pr) and
            "autonomy:cto-implementation" in labels):
        return "cto"
    return None


def current_pr_for_sha(open_prs: list[dict[str, Any]], sha: str) -> dict[str, Any] | None:
    matches = [pr for pr in open_prs if pr.get("head", {}).get("sha") == sha]
    eligible = [pr for pr in matches if automation_kind(pr)]
    return eligible[0] if len(eligible) == 1 else None


def admit_waiting_runs(open_prs: list[dict[str, Any]]) -> None:
    payload = get(f"/repos/{REPO}/actions/runs?status=action_required&per_page=100")
    runs = payload.get("workflow_runs", []) if isinstance(payload, dict) else []
    carriers = [source for source in open_prs if is_carrier(source)]
    for run in runs:
        sha = str(run.get("head_sha", ""))
        pr = current_pr_for_sha(open_prs, sha)
        if pr is None:
            continue
        kind = automation_kind(pr)
        if kind == "kilo" and (linked_kilo_carrier(pr, carriers) is None and
                                linked_kilo_review_source(pr, open_prs) is None):
            continue
        run_id = int(run["id"])
        name = str(run.get("name", "workflow"))
        try:
            post(f"/repos/{REPO}/actions/runs/{run_id}/approve", expected=(201,))
            log(f"Approved waiting {name} run {run_id} for trusted {kind} PR #{pr['number']}.")
            continue
        except ApiError as exc:
            if exc.status not in (403, 404, 409, 422):
                raise
            log(f"Approval endpoint did not accept run {run_id} ({exc.status}); trying safe rerun for the same trusted PR.")
        try:
            post(f"/repos/{REPO}/actions/runs/{run_id}/rerun", expected=(201,))
            log(f"Re-requested {name} run {run_id} for trusted {kind} PR #{pr['number']}.")
        except ApiError as exc:
            log(f"Could not automatically admit run {run_id}: {exc}")


def latest_runs_for_sha(sha: str) -> dict[str, dict[str, Any]]:
    query = urllib.parse.urlencode({"head_sha": sha, "event": "pull_request", "per_page": 100})
    payload = get(f"/repos/{REPO}/actions/runs?{query}")
    latest: dict[str, dict[str, Any]] = {}
    for run in payload.get("workflow_runs", []):
        name = str(run.get("name", ""))
        current = latest.get(name)
        if current is None or int(run.get("id", 0)) > int(current.get("id", 0)):
            latest[name] = run
    return latest


def all_required_checks_green(pr: dict[str, Any]) -> tuple[bool, str]:
    sha = str(pr.get("head", {}).get("sha", ""))
    runs = latest_runs_for_sha(sha)
    for name in REQUIRED_WORKFLOWS:
        run = runs.get(name)
        if run is None:
            return False, f"required workflow {name!r} has not run on {sha[:12]}"
        if run.get("status") != "completed" or run.get("conclusion") != "success":
            return False, f"required workflow {name!r} is {run.get('status')}/{run.get('conclusion')}"

    # GitHub's native ruleset/auto-merge checks any additional required contexts.
    # Optional review, link and external-service checks cannot become an extra gate here.
    return True, "required CI and security workflows succeeded"


def pr_files(number: int) -> list[str]:
    names: list[str] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/pulls/{number}/files?per_page=100&page={page}")
        names.extend(str(item.get("filename", "")) for item in chunk)
        if len(chunk) < 100:
            return names
    raise RuntimeError(f"PR #{number} has too many changed files to verify safely")


def sensitive_file(path: str) -> bool:
    if path in KILO_SENSITIVE_EXACT:
        return True
    return any(path == prefix or path.startswith(prefix) for prefix in KILO_SENSITIVE_PREFIXES)


def place_human_hold(pr: dict[str, Any], reason: str) -> None:
    labels = issue_labels(pr)
    if "autonomy:human-hold" not in labels:
        add_labels(int(pr["number"]), ["autonomy:human-hold"])
        comment(int(pr["number"]), f"Trusted automation stopped here and applied `autonomy:human-hold`: {reason}")
    log(f"PR #{pr['number']} requires human review: {reason}")


def current_head_unchanged(number: int, expected_sha: str) -> dict[str, Any] | None:
    current = get(f"/repos/{REPO}/pulls/{number}")
    if current.get("state") != "open" or current.get("head", {}).get("sha") != expected_sha:
        return None
    return current


def has_current_approval(number: int, sha: str) -> bool:
    reviews = get(f"/repos/{REPO}/pulls/{number}/reviews?per_page=100")
    return any(r.get("state") == "APPROVED" and r.get("commit_id") == sha for r in reviews)


def approve_pr(number: int, sha: str) -> None:
    if has_current_approval(number, sha):
        return
    post(
        f"/repos/{REPO}/pulls/{number}/reviews",
        {
            "event": "APPROVE",
            "body": "Trusted automation approval: exact-head CI, CodeQL and repository security checks passed.",
            "commit_id": sha,
        },
        expected=(200, 201),
    )
    log(f"Approved PR #{number} at {sha[:12]} after trusted checks passed.")


def admit_to_mergify(number: int) -> None:
    pr = get(f"/repos/{REPO}/pulls/{number}")
    if pr.get("state") != "open":
        return
    labels = issue_labels(pr)
    blocking = labels.intersection(BLOCKING_LABELS)
    if blocking:
        if "autonomy:admitted" in labels:
            encoded = urllib.parse.quote("autonomy:admitted", safe="")
            delete(f"/repos/{REPO}/issues/{number}/labels/{encoded}", expected=(200, 204))
        log(f"PR #{number} admission withheld by blocking label(s): {', '.join(sorted(blocking))}.")
        return
    if "autonomy:admitted" in labels:
        log(f"PR #{number} is already admitted to Mergify.")
        return
    add_labels(number, ["autonomy:admitted"])
    log(f"Admitted PR #{number} to Mergify after exact-head CI, CodeQL and security verification.")


def reconcile_stale_carriers(open_prs: list[dict[str, Any]]) -> None:
    """Close verified retired carriers directly, without waiting for Mergify.

    Retired carrier branches are retained as failure evidence. Implementations
    and arbitrary PRs are never closed by this lifecycle reconciler.
    """
    branch = get(f"/repos/{REPO}/branches/{DEFAULT_BRANCH}")
    current_main_sha = str(branch.get("commit", {}).get("sha", ""))
    if not re.fullmatch(r"[0-9a-f]{40}", current_main_sha):
        raise RuntimeError("Could not resolve the current default-branch SHA")

    for pr in open_prs:
        if not is_repair_carrier_identity(pr):
            continue
        labels = issue_labels(pr)
        retired = bool(labels.intersection({"autonomy:superseded", "autonomy:obsolete"}))
        match = re.search(r"Failed commit:\s*`([0-9a-f]{40})`", str(pr.get("body") or ""))
        if not retired and (match is None or match.group(1) == current_main_sha):
            continue
        number = int(pr["number"])
        if not retired:
            add_labels(number, ["autonomy:obsolete"])
        request("PATCH", f"/repos/{REPO}/pulls/{number}", {"state": "closed"})
        # Close before removing active labels so a failed close remains retryable.
        for label in ("autonomy:human-hold", "autonomy:repair", "autonomy:admitted"):
            if label in labels:
                encoded = urllib.parse.quote(label, safe="")
                delete(f"/repos/{REPO}/issues/{number}/labels/{encoded}", expected=(200, 204))
        log(f"Closed retired repair carrier PR #{number}.")


def reconcile_pr(pr: dict[str, Any]) -> None:
    kind = automation_kind(pr)
    if kind is None or pr.get("draft"):
        return
    labels = issue_labels(pr)
    blocking = labels.intersection(BLOCKING_LABELS)
    if blocking:
        if "autonomy:admitted" in labels:
            encoded = urllib.parse.quote("autonomy:admitted", safe="")
            delete(
                f"/repos/{REPO}/issues/{int(pr['number'])}/labels/{encoded}",
                expected=(200, 204),
            )
            log(
                f"Withdrew Mergify admission for PR #{pr['number']} because of "
                f"blocking label(s): {', '.join(sorted(blocking))}."
            )
        return
    if kind == "carrier":
        # Carriers record the failed run and remain blocked until the linked
        # implementation succeeds. Never merge one just because its marker was removed.
        log(f"Carrier PR #{pr['number']} is lifecycle evidence; withholding auto-merge.")
        return

    if kind == "renovate" and not renovate_auto_eligible(pr):
        # Renovate eligibility is explicit metadata; manual/unlabelled updates remain human merge decisions.
        return

    if kind in {"kilo", "cto", "branch-pr"}:
        sensitive = [path for path in pr_files(int(pr["number"])) if sensitive_file(path)]
        if sensitive:
            source = "repair" if kind == "kilo" else ("cto.new" if kind == "cto" else "managed branch")
            place_human_hold(
                pr,
                f"the {source} PR changes governance/security automation files: " + ", ".join(sensitive[:8]),
            )
            return

    if kind == "kilo":
        carriers = [source for source in list_open_prs() if is_carrier(source)]
        source_number = linked_kilo_carrier(pr, carriers)
        if source_number is None:
            source_number = linked_kilo_review_source(pr, list_open_prs())
        if source_number is None:
            log(f"Kilo PR #{pr['number']} no longer has a current verified source; withholding merge.")
            return
        leases = active_leases_for_issue(source_number, "kilo")
        if len(leases) != 1:
            log(f"Kilo PR #{pr['number']} has no single active durable Kilo lease; withholding merge.")
            return
        if leases[0].get("implementation_pr") != int(pr["number"]):
            bind_lease(source_number, "kilo", str(leases[0]["fingerprint"]), int(pr["number"]))

    if kind == "cto":
        linked = linked_cto_issue(pr)
        if linked is None:
            log(f"cto.new PR #{pr['number']} no longer has a current verified task/lease; withholding merge.")
            return
        issue_number, lease = linked
        if lease.get("implementation_pr") != int(pr["number"]):
            bind_lease(issue_number, "cto", str(lease["fingerprint"]), int(pr["number"]))

    green, reason = all_required_checks_green(pr)
    if not green:
        log(f"PR #{pr['number']} ({kind}) not ready: {reason}.")
        return

    number = int(pr["number"])
    sha = str(pr.get("head", {}).get("sha", ""))
    current = current_head_unchanged(number, sha)
    if current is None:
        log(f"PR #{number} changed while being evaluated; waiting for the next reconciliation.")
        return

    # Renovate and Kilo are distinct identities, so the repair App can provide the trusted review.
    # Carrier PRs are authored by the same repair App and GitHub correctly forbids self-approval.
    if kind in {"renovate", "kilo", "cto"}:
        approve_pr(number, sha)
        if current_head_unchanged(number, sha) is None:
            return

    admit_to_mergify(number)


def main() -> int:
    if not REQUIRED_WORKFLOWS:
        raise RuntimeError("REQUIRED_WORKFLOWS must list the repository's CI/security workflow names")
    if not re.fullmatch(r"[A-Za-z0-9-]+\[bot\]", REPAIR_APP_LOGIN):
        raise RuntimeError("REPAIR_APP_LOGIN must be the installed repair GitHub App bot login")
    if (not re.fullmatch(r"[A-Za-z0-9-]+(?:\[bot\])?", KILO_LOGIN) or
            KILO_LOGIN in {REPAIR_APP_LOGIN, RENOVATE_LOGIN, "github-actions[bot]"}):
        raise RuntimeError("KILO_REPAIR_PR_LOGIN must name the distinct, verified Kilo PR creator")
    ensure_label("dependency:auto-eligible", "0E8A16", "Renovate update class is eligible for trusted admission after exact-head gates")
    ensure_label("dependency:manual", "FBCA04", "Renovate update class requires a human merge decision")
    ensure_label("autonomy:kilo-implementation", "5319E7", "Kilo implementation PR linked to an autonomous repair carrier")
    ensure_label("autonomy:cto-task", "1D76DB", "Real actionable issue intentionally handed to cto.new")
    ensure_label("autonomy:cto-implementation", "1D76DB", "cto.new implementation PR linked to a verified actionable issue")
    ensure_label("autonomy:human-hold", "FBCA04", "Automation must stop for human action")
    ensure_label("autonomy:obsolete", "D4C5F9", "Repair carrier is no longer current")
    ensure_label("autonomy:admitted", "0E8A16", "Exact-head CI/security verification complete; Mergify may merge")

    reconcile_completed_leases()
    reconcile_cto_tasks()
    open_prs = list_open_prs()
    reconcile_stale_carriers(open_prs)
    open_prs = list_open_prs()  # refresh after stale-carrier lifecycle changes
    adopt_linked_kilo_prs(open_prs)
    adopt_linked_cto_prs(open_prs)
    open_prs = list_open_prs()  # refresh labels after external-agent correlation
    admit_waiting_runs(open_prs)

    # Reconcile current trusted PRs. Runs admitted above will normally become ready on a later
    # workflow_run completion or scheduled reconciliation.
    for pr in open_prs:
        reconcile_pr(pr)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"::error::{exc}", file=sys.stderr)
        raise
