import { fetchPodcastEpisodes, cleanText } from "../_shared/podcast.js";
import { ensureSharedChrome } from "../_shared/chrome.js";
const SITE='https://jonathan-harris.online';
function slugParts(params){const raw=Array.isArray(params?.slug)?params.slug.join('/'):String(params?.slug||'');return raw.replace(/^\/+|\/+$/g,'')}
function esc(v=''){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function displayText(v=''){return String(v||'').replace(/\b\d+\s*(?:-|–|—)?\s*minutes?\b/gi,'').replace(/\b\d+\s*mins?\b/gi,'').replace(/\b\d{1,2}:\d{2}(?::\d{2})?\b/g,'').replace(/\bthis\s+week(?:[’']s)?\b/gi,'').replace(/\bweekly\s+(briefing|analysis|round-?up|update)\b/gi,'$1').replace(/\s+([,.;:!?])/g,'$1').replace(/\s{2,}/g,' ').replace(/^[\s,;:–—-]+|[\s,;:–—-]+$/g,'')}
function cards(episodes){return episodes.map(ep=>`<article class="card podcast-latest-card" data-episode-slug="${esc(ep.slug)}"><h3>${esc(ep.title)}</h3><p>${esc(displayText(ep.teaser))}</p><div class="actions"><a class="button" href="${esc(ep.episode_url)}" data-placement="podcast_latest">Listen</a>${ep.transcript_url?`<a class="button secondary" href="${esc(ep.transcript_url)}" data-placement="podcast_latest">Read transcript</a>`:''}</div></article>`).join('')}
async function relatedBooks(context,episodes,topic){try{const url=new URL('/api/v1/books.json',context.request.url),r=context.env?.ASSETS?await context.env.ASSETS.fetch(new Request(url)):await fetch(url);if(!r.ok)return'';const books=await r.json(),tokens=new Set(`${topic} ${episodes.map(e=>e.title+' '+e.teaser).join(' ')}`.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>3));const ranked=books.map(b=>{const hay=`${b.title} ${b.topic} ${(b.tags||[]).join(' ')}`.toLowerCase();let score=0;for(const t of tokens)if(hay.includes(t))score++;if(topic&&String(b.topic_slug||'')===topic)score+=10;return{b,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||String(a.b.title).localeCompare(String(b.b.title))).slice(0,2);if(!ranked.length)return'';return `<section class="card podcast-related-reading"><h2>Related reading</h2><div class="jh-journey-actions">${ranked.map(({b})=>`<a href="/ebooks/${esc(b.slug)}/" data-book-slug="${esc(b.slug)}" data-placement="podcast_related">${esc(b.title)}</a>`).join('')}</div></section>`}catch{return''}}
async function renderLanding(context){const response=await context.next();if(!response.headers.get('content-type')?.includes('text/html'))return response;let text=await response.text();try{const topic=new URL(context.request.url).searchParams.get('topic')||'',result=await fetchPodcastEpisodes(context.env,context.request,12);let eps=result.episodes;if(topic){const bits=topic.replace(/-/g,' ').split(/\s+/).filter(Boolean);const filtered=eps.filter(ep=>bits.some(b=>`${ep.title} ${ep.description}`.toLowerCase().includes(b)));if(filtered.length)eps=filtered}eps=eps.slice(0,3);const block=eps.length?`<div class="grid podcast-latest-grid">${cards(eps)}</div>`:'<p>Episode details are temporarily unavailable. Use the platform links or transcript archive.</p>';text=text.replace(/<div data-podcast-latest-server>[\s\S]*?<\/div>/i,`<div data-podcast-latest-server>${block}</div>`);text=text.replace('</main>',`${await relatedBooks(context,eps,topic)}</main>`)}catch{}text=await ensureSharedChrome(context,text);const headers=new Headers(response.headers);headers.set('Cache-Control','public, max-age=300, stale-while-revalidate=1800');return new Response(text,{status:response.status,statusText:response.statusText,headers})}
export async function onRequest(context){const slug=slugParts(context.params);if(!slug)return renderLanding(context);if(!/^TT-\d{4}-\d{2}-\d{2}\/?$/i.test(slug))return context.next();try{const{episodes}=await fetchPodcastEpisodes(context.env,context.request,100),needle=slug.replace(/\/$/,'');const match=episodes.find(ep=>`${ep.guid} ${ep.audio_url} ${ep.transcript_url}`.includes(needle));if(match?.episode_url)return Response.redirect(match.episode_url,301)}catch{}return Response.redirect(new URL('/podcast/',context.request.url).toString(),301)}
